@startuml
interface Filter {
  + accept(x: Object) : boolean
}

class ShortWordFilter {
  + accept(x: Object) : boolean
}

class BigRectangleFilter {
  + accept(x: Object) : boolean
}

ShortWordFilter ..|> Filter
BigRectangleFilter ..|> Filter
@enduml

