@startuml
skinparam backgroundColor white
skinparam classAttributeIconSize 0

class Person {
  - firstName: String
  - lastName: String
  - ID: String
  - title: String
  - YOB: int
  --
  + Person(firstName:String, lastName:String, ID:String, title:String, YOB:int)
  + Person(ID:String)
  + getFirstName(): String
  + setFirstName(String): void
  + getLastName(): String
  + setLastName(String): void
  + getID(): String
  + setID(String): void
  + getTitle(): String
  + setTitle(String): void
  + getYOB(): int
  + setYOB(int): void
  + fullName(): String
  + formalName(): String
  + getAge(): String
  + getAge(year:int): String
  + toCSV(): String
  + toJSON(): String
  + toXML(): String
  + toString(): String
  + equals(Object): boolean
  + hashCode(): int
}

class Product {
  - name: String
  - description: String
  - ID: String
  - cost: double
  --
  + Product(name:String, description:String, ID:String, cost:double)
  + Product(ID:String)
  + getName(): String
  + setName(String): void
  + getDescription(): String
  + setDescription(String): void
  + getID(): String
  + setID(String): void
  + getCost(): double
  + setCost(double): void
  + toCSV(): String
  + toJSON(): String
  + toXML(): String
  + toString(): String
  + equals(Object): boolean
  + hashCode(): int
}

class SafeInputObj {
  - pipe: Scanner
  --
  + SafeInputObj()
  + SafeInputObj(scanner:Scanner)
  + getNonZeroLenString(prompt:String): String
  + getRangedInt(prompt:String, low:int, high:int): int
  + getInt(prompt:String): int
  + getRangedDouble(prompt:String, low:int, high:int): double
  + getDouble(prompt:String): double
  + getYNConfirm(prompt:String): boolean
  + getRegExString(prompt:String, regExPattern:String): String
}
@enduml
